# Generated by Django 4.0.4 on 2022-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Arts & Crafts', 'Arts & Crafts'), ('Collecting', 'Collecting'), ('Foodie', 'Foodie'), ('Games', 'Games'), ('Lucrative', 'Lucrative'), ('Music', 'Music'), ('Outdoors', 'Outdoors'), ('Performing Arts', 'Performing Arts'), ('Pets', 'Pets'), ('Sports', 'Sports'), ('Spiritual & Mental', 'Spiritual & Mental'), ('Travel', 'Travel')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
