# Generated by Django 4.0.4 on 2022-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
